#!/usr/bin/env bash
# Generate pkgbuild/linux-lts-mbp from Arch's official linux-lts packaging plus this repo's MacBookPro11,3 patches.
# LTS only: mainline moves too fast to keep the patch series ported.
#
#   ./mkpkgbuild.sh                      # latest Arch linux-lts
#   ./mkpkgbuild.sh 6.18.55-1            # pin an Arch packaging tag
#   ./mkpkgbuild.sh --prepare            # also extract + apply all patches on the real tree (no build)
#
# Patch series: patches/kernel/*.patch, except 0005 (i915 eDP retry), which is taken from
# patches/kernel-<major.minor>/0005-*.patch because its context differs per kernel series.
set -euo pipefail

base=linux-lts
tag=""
prepare=0
for a in "$@"; do
  case $a in
    --prepare) prepare=1 ;;
    -*) echo "unknown option: $a" >&2; exit 1 ;;
    *) tag=$a ;;
  esac
done

here=$(cd "$(dirname "$0")" && pwd)
repo=$(dirname "$here")
dest="$here/$base-mbp"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

echo "==> Fetching Arch packaging for $base ${tag:-(latest)}"
git clone -q "https://gitlab.archlinux.org/archlinux/packaging/packages/$base.git" "$tmp/arch"
[[ -n $tag ]] && git -C "$tmp/arch" checkout -q "$tag"
pkgver=$(cd "$tmp/arch" && bash -c 'source PKGBUILD >/dev/null 2>&1; echo "$pkgver-$pkgrel"')
[[ $pkgver =~ ^[0-9]+\.[0-9]+ ]] || { echo "ERROR: could not read pkgver from Arch PKGBUILD (got '$pkgver')" >&2; exit 1; }
series=$(cut -d. -f1,2 <<<"$pkgver")
echo "    Arch $base $pkgver (series $series)"

shopt -s nullglob
port=("$repo/patches/kernel-$series"/0005-*.patch)
[[ ${#port[@]} -eq 1 ]] || {
  echo "ERROR: no 0005 port for kernel $series in patches/kernel-$series/ — port it first" >&2
  exit 1
}

echo "==> Refreshing $dest"
mkdir -p "$dest"
cd "$dest"
rm -rf PKGBUILD config.* ./*.patch mbp-*.patch keys LICENSE LICENSES REUSE.toml
cp -a "$tmp/arch"/{PKGBUILD,config.x86_64,keys,LICENSE,LICENSES,REUSE.toml} .
arch_patches=("$tmp/arch"/*.patch)
(( ${#arch_patches[@]} )) && cp "${arch_patches[@]}" .

links=()
for f in "$repo"/patches/kernel/*.patch; do
  name=$(basename "$f")
  if [[ $name == 0005-* ]]; then
    f=${port[0]}
    name=$(basename "$f")
  fi
  ln -s "$(realpath --relative-to="$dest" "$f")" "mbp-$name"
  links+=("mbp-$name")
done
printf '%s\n' '# makepkg artifacts (generated by mkpkgbuild.sh)' 'src/' 'pkg/' '*.tar.xz' '*.tar.sign' \
  '*.patch.zst' '*.patch.zst.sig' '*.pkg.tar.zst' '*.log' > .gitignore

echo "==> Patching PKGBUILD"
python3 - PKGBUILD "$base" "${links[@]}" <<'EOF'
import hashlib, re, sys
path, base, links = sys.argv[1], sys.argv[2], sys.argv[3:]
s = open(path).read()

def sub(pattern, repl, flags=re.M):
    global s
    s, n = re.subn(pattern, repl, s, flags=flags)
    if n != 1:
        sys.exit(f"PKGBUILD layout changed: pattern matched {n}x: {pattern!r}")

sub(r"^pkgbase=linux-lts$", f"pkgbase={base}-mbp")
sub(r"^pkgdesc='(.*)'$", r"pkgdesc='\1 (MacBookPro11,3 gmux/nouveau patches)'")
sub(r"\n\n  # htmldocs\n(?:  \S+\n)+", "\n")
sub(r"^  make htmldocs SPHINXOPTS=-QT &\n  local pid_docs=\$!\n\n", "")
sub(r"^  wait \$pid_docs\n", "")
sub(r"^  replaces=\(\n(?:    \S+\n)+  \)\n\n", "")
sub(r'^  "\$pkgbase-docs"\n', "")
src = "".join(f"  {l}\n" for l in links)
sub(r"^(source=\(\n(?:  .*\n)*?)\)", lambda m: m.group(1) + src + ")")

for arr, algo, pad in (("sha256sums", "sha256", 12), ("b2sums", "blake2b", 8)):
    if not re.search(rf"^{arr}=\(", s, re.M):
        continue
    sums = "".join(f"\n{' ' * pad}'{getattr(hashlib, algo)(open(l, 'rb').read()).hexdigest()}'" for l in links)
    sub(rf"^({arr}=\((?:.|\n)*?)\)", lambda m: m.group(1) + sums + ")")
open(path, "w").write(s)
EOF
bash -n PKGBUILD

echo "==> Importing kernel signing keys"
keyfiles=(keys/pgp/*.asc)
(( ${#keyfiles[@]} )) || { echo "ERROR: no signing keys in keys/pgp/" >&2; exit 1; }
gpg --quiet --import "${keyfiles[@]}"

echo "==> Verifying sources"
makepkg --verifysource

if (( prepare )); then
  echo "==> Extracting and applying all patches (prepare only)"
  makepkg -o --nodeps -C
fi

echo "==> Ready: $dest ($base-mbp $pkgver). Build with: cd $dest && makepkg -sfC"
